_extends: private-global-settings

branches:
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts: [ "ci/circleci: build" ]

collaborators:
  - username: willscott
    permission: admin
