[package]
name = "deoxysii-rust"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Deoxys-II-256-128 MRAE primitives for Rust"
repository = "https://github.com/oasislabs/deoxysii-rust"
edition = "2018"
publish = false

[dependencies]
failure = "0.1.5"
subtle = "2.0.0"
zeroize = "0.6.0"

[dev-dependencies]
rand = "0.6.5"
serde_json = "1.0.39"
base64 = "0.10.1"
